pub const REPL_COMMANDS: &[&str] = &[
    "/help",
    "/new",
    "/resume",
    "/compact",
    "/clear",
    "/model",
    "/providers",
    "/config",
    "/ps",
    "/thinking",
    "/audit",
    "/plan",
    "/yolo",
    "/undo",
    "/exit",
];
